# Generated by Django 5.2.3 on 2025-07-11 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(blank=True, help_text='same RecipeSpanish data', max_length=50, null=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/recipes/')),
                ('recipe_name', models.CharField(max_length=255)),
                ('recipe_type', models.CharField(max_length=50)),
                ('for_time', models.CharField(max_length=50)),
                ('tag', models.CharField(blank=True, max_length=200)),
                ('calories', models.DecimalField(decimal_places=2, max_digits=6)),
                ('carbs', models.DecimalField(decimal_places=2, max_digits=6)),
                ('protein', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fat', models.DecimalField(decimal_places=2, max_digits=6)),
                ('making_time', models.DurationField(help_text='Time needed to make the recipe (hh:mm:ss)')),
                ('time', models.DurationField(help_text='Additional time or total time (hh:mm:ss)')),
                ('ratings', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('category', models.CharField(max_length=50)),
                ('ingredients', models.TextField(help_text='List ingredients separated by commas or lines.')),
                ('instructions', models.TextField(help_text='Step-by-step cooking instructions.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeSpanish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(blank=True, help_text='same Recipe data', max_length=100, null=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/recipes/')),
                ('recipe_name', models.CharField(max_length=255)),
                ('recipe_type', models.CharField(max_length=50)),
                ('for_time', models.CharField(max_length=50)),
                ('tag', models.CharField(blank=True, max_length=200)),
                ('calories', models.DecimalField(decimal_places=2, max_digits=6)),
                ('carbs', models.DecimalField(decimal_places=2, max_digits=6)),
                ('protein', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fat', models.DecimalField(decimal_places=2, max_digits=6)),
                ('making_time', models.DurationField(help_text='Tiempo necesario para preparar la receta (hh:mm:ss)')),
                ('time', models.DurationField(help_text='Tiempo adicional o total (hh:mm:ss)')),
                ('ratings', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('category', models.CharField(max_length=50)),
                ('ingredients', models.TextField(help_text='Lista de ingredientes separados por comas o líneas.')),
                ('instructions', models.TextField(help_text='Instrucciones paso a paso para cocinar.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
