# Generated by Django 5.2.3 on 2025-07-11 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_alter_recipe_calories_alter_recipe_carbs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipespanish',
            name='calories',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='recipespanish',
            name='carbs',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='recipespanish',
            name='fat',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='recipespanish',
            name='protein',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
