# Generated by Django 5.2.3 on 2025-07-11 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_alter_recipespanish_calories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='unique_id',
            field=models.CharField(blank=True, help_text='same RecipeSpanish data', max_length=100, null=True, unique=True),
        ),
    ]
