# Generated by Django 5.2.3 on 2025-08-06 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_alter_recipe_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='for_time',
            field=models.CharField(max_length=150),
        ),
    ]
