# Generated by Django 5.2.3 on 2025-07-24 03:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meal', '0006_mealentry_cancelled_mealentry_eating_time'),
        ('workoutplan', '0004_dailyworkout_tags_spanish_dailyworkout_title_spanish'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_weight', models.FloatField(blank=True, null=True)),
                ('abdominal', models.FloatField(blank=True, null=True)),
                ('sacroiliac', models.FloatField(blank=True, null=True)),
                ('subscapularis', models.FloatField(blank=True, null=True)),
                ('triceps', models.FloatField(blank=True, null=True)),
                ('feeling', models.CharField(blank=True, max_length=100, null=True)),
                ('total_meal', models.IntegerField(blank=True, null=True)),
                ('workout_consistency', models.IntegerField(blank=True, null=True)),
                ('energy_level', models.IntegerField(blank=True, null=True)),
                ('injuries_pain', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meal_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fitness_profiles', to='meal.mealplan')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fitness_profiles', to=settings.AUTH_USER_MODEL)),
                ('workout_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fitness_profiles', to='workoutplan.workoutplan')),
            ],
            options={
                'verbose_name': 'Fitness Profile',
                'verbose_name_plural': 'Fitness Profiles',
            },
        ),
    ]
