# Generated by Django 5.2.3 on 2025-07-25 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('completeinfo', '0002_achievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='achievement_date',
            field=models.DateField(auto_now=True),
        ),
    ]
