# Generated by Django 5.2.3 on 2025-07-26 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('completeinfo', '0003_achievement_achievement_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='weight_increase',
            field=models.BooleanField(default=False, help_text='True if Weight measurement is an increase, False for decrease'),
        ),
    ]
