# Generated by Django 5.2.3 on 2025-07-30 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('completeinfo', '0004_alter_achievement_weight_increase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnessprofile',
            name='workout_consistency',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
