# Generated by Django 5.2.1 on 2025-07-14 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_workoutspanish_workout_unique_id'),
        ('workoutplan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyworkout',
            name='completed',
            field=models.BooleanField(default=False, help_text='Mark if the workout is completed'),
        ),
        migrations.AddField(
            model_name='dailyworkout',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags', max_length=255),
        ),
        migrations.AddField(
            model_name='dailyworkout',
            name='title',
            field=models.CharField(default=1, help_text='Title for the daily workout', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workoutentry',
            name='set_of',
            field=models.PositiveIntegerField(default=1, help_text='Number of sets performed'),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags for the meal plan', max_length=255),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='workout_plan_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workoutentry',
            name='workout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workout.workout', to_field='unique_id'),
        ),
    ]
