# Generated by Django 5.2.1 on 2025-07-15 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workoutplan', '0002_dailyworkout_completed_dailyworkout_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutentry',
            name='reps',
            field=models.PositiveIntegerField(default=10, help_text='Repetitions per set'),
        ),
    ]
