# Generated by Django 5.2.3 on 2025-07-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workoutplan', '0003_workoutentry_reps'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyworkout',
            name='tags_spanish',
            field=models.CharField(blank=True, help_text='Etiquetas separadas por comas en español', max_length=255),
        ),
        migrations.AddField(
            model_name='dailyworkout',
            name='title_spanish',
            field=models.CharField(blank=True, help_text='Título del entrenamiento diario en español', max_length=255),
        ),
    ]
