# Generated by Django 5.2.3 on 2025-07-09 04:19

import django.db.models.deletion
import multiselectfield.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role_passwordresetotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileSpanish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/user_images/')),
                ('fullname', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre completo')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Masculino'), ('female', 'Femenino')], max_length=15, null=True, verbose_name='Género')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='Peso')),
                ('height', models.FloatField(blank=True, null=True, verbose_name='Altura')),
                ('abdominal', models.FloatField(blank=True, null=True, verbose_name='Abdominales')),
                ('sacroiliac', models.FloatField(blank=True, null=True, verbose_name='Sacroilíaco')),
                ('subscapularis', models.FloatField(blank=True, null=True, verbose_name='Subescapular')),
                ('triceps', models.FloatField(blank=True, null=True, verbose_name='Tríceps')),
                ('fitness_level', models.CharField(blank=True, choices=[('Beginners', 'Principiante'), ('Basic', 'Básico'), ('Intermediate', 'Intermedio'), ('High', 'Avanzado')], max_length=20, null=True, verbose_name='Nivel de forma física')),
                ('trainer', models.CharField(blank=True, choices=[('At home', 'En casa'), ('At gym', 'En el gimnasio'), ('Martial arts', 'Artes marciales'), ('Running', 'Correr'), ('Other sports', 'Otros deportes')], max_length=30, null=True, verbose_name='Entrenador')),
                ('at_home', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Dumbbells', 'Mancuernas'), ('Resistance bands', 'Bandas de resistencia'), ('Pull-up bar', 'Barra de dominadas'), ('Bench', 'Banco'), ('No equipment', 'Sin equipo')], max_length=100, null=True, verbose_name='Equipo en casa')),
                ('at_gym', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Barbell', 'Barra'), ('Squat rack', 'Rack de sentadillas'), ('Cable machine', 'Máquina de cables'), ('Smith machine', 'Máquina Smith')], max_length=100, null=True, verbose_name='Equipo en el gimnasio')),
                ('martial_arts', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Running', 'Correr'), ('Football', 'Fútbol'), ('Swimming', 'Natación')], max_length=100, null=True, verbose_name='Artes marciales')),
                ('running', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Running', 'Correr'), ('Football', 'Fútbol'), ('Swimming', 'Natación')], max_length=100, null=True, verbose_name='Correr')),
                ('other_sports', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Running', 'Correr'), ('Football', 'Fútbol'), ('Swimming', 'Natación')], max_length=100, null=True, verbose_name='Otros deportes')),
                ('train_duration', models.CharField(blank=True, max_length=100, null=True, verbose_name='Duración del entrenamiento')),
                ('interested_workout', models.CharField(blank=True, choices=[('Lose Fat', 'Perder grasa'), ('Gain Muscle', 'Ganar músculo (solo si el % ya es bajo)'), ('Maintenance', 'Mantenimiento')], max_length=50, null=True, verbose_name='Objetivo del entrenamiento')),
                ('injuries_discomfort', models.TextField(blank=True, null=True, verbose_name='Lesiones o molestias')),
                ('routine_duration', models.CharField(blank=True, choices=[('1 Month', '1 Mes'), ('2 Month', '2 Meses'), ('3 Month', '3 Meses'), ('6 Month', '6 Meses'), ('1 Year', '1 Año')], max_length=20, null=True, verbose_name='Duración de la rutina')),
                ('dietary_preferences', models.CharField(blank=True, choices=[('Keto', 'Keto'), ('Paleo', 'Paleo'), ('Vegetarian', 'Vegetariano'), ('Vegan', 'Vegano'), ('Gluten-Free', 'Sin gluten'), ('No preferences', 'Sin preferencias')], max_length=30, null=True, verbose_name='Preferencias dietéticas')),
                ('allergies', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Nuts', 'Nueces'), ('Dairy', 'Lácteos'), ('Shellfish', 'Mariscos'), ('Eggs', 'Huevos'), ('No allergies', 'Sin alergias')], max_length=100, null=True, verbose_name='Alergias')),
                ('food_preference', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Egg', 'Huevo'), ('Milk', 'Leche'), ('Fish', 'Pescado')], max_length=100, null=True, verbose_name='Preferencias alimenticias')),
                ('medical_conditions', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Diabetes', 'Diabetes'), ('High blood pressure', 'Presión arterial alta'), ('Heart disease', 'Enfermedad cardíaca')], max_length=100, null=True, verbose_name='Condiciones médicas')),
                ('fitness_goals', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Weight loss', 'Pérdida de peso'), ('Weight gain', 'Aumento de peso'), ('Maintenance', 'Mantenimiento')], max_length=100, null=True, verbose_name='Objetivos de fitness')),
                ('lifestyle_habits', models.CharField(blank=True, choices=[('3 Meals', '3 comidas'), ('4 Meals', '4 comidas'), ('5 Meals', '5 comidas'), ('6 Meals', '6 comidas'), ('7 Meals', '7 comidas'), ('8 Meals', '8 comidas')], max_length=20, null=True, verbose_name='Hábitos alimenticios')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_spanish', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
