# Generated by Django 5.2.3 on 2025-07-09 08:33

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profilespanish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilespanish',
            name='allergies',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Nueces', 'Nueces'), ('Lácteos', 'Lácteos'), ('Mariscos', 'Mariscos'), ('Huevos', 'Huevos'), ('Sin alergias', 'Sin alergias')], max_length=100, null=True, verbose_name='Alergias'),
        ),
        migrations.AlterField(
            model_name='profilespanish',
            name='at_gym',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Barra', 'Barra'), ('Rack de sentadillas', 'Rack de sentadillas'), ('Máquina de cables', 'Máquina de cables'), ('Máquina Smith', 'Máquina Smith')], max_length=100, null=True, verbose_name='Equipo en el gimnasio'),
        ),
        migrations.AlterField(
            model_name='profilespanish',
            name='at_home',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Mancuernas', 'Mancuernas'), ('Bandas de resistencia', 'Bandas de resistencia'), ('Barra de dominadas', 'Barra de dominadas'), ('Banco', 'Banco'), ('Sin equipo', 'Sin equipo')], max_length=100, null=True, verbose_name='Equipo en casa'),
        ),
        migrations.AlterField(
            model_name='profilespanish',
            name='dietary_preferences',
            field=models.CharField(blank=True, choices=[('Keto', 'Keto'), ('Paleo', 'Paleo'), ('Vegetariano', 'Vegetariano'), ('Vegano', 'Vegano'), ('Sin gluten', 'Sin gluten'), ('Sin preferencias', 'Sin preferencias')], max_length=30, null=True, verbose_name='Preferencias dietéticas'),
        ),
        migrations.AlterField(
            model_name='profilespanish',
            name='fitness_goals',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Pérdida de peso', 'Pérdida de peso'), ('Aumento de peso', 'Aumento de peso'), ('Mantenimiento', 'Mantenimiento')], max_length=100, null=True, verbose_name='Objetivos de fitness'),
        ),
        migrations.AlterField(
            model_name='profilespanish',
            name='fitness_level',
            field=models.CharField(blank=True, choices=[('Principiante', 'Principiante'), ('Básico', 'Básico'), ('Intermedio', 'Intermedio'), ('Avanzado', 'Avanzado')], max_length=20, null=True, verbose_name='Nivel de forma física'),
        ),
        migrations.AlterField(
            model_name='profilespanish',
            name='food_preference',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Huevo', 'Huevo'), ('Leche', 'Leche'), ('Pescado', 'Pescado')], max_length=100, null=True, verbose_name='Preferencias alimenticias'),
        ),
        migrations.AlterField(
            model_name='profilespanish',
            name='gender',
            field=models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=15, null=True, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='profilespanish',
            name='interested_workout',
            field=models.CharField(blank=True, choices=[('Perder grasa', 'Perder grasa'), ('Ganar músculo', 'Ganar músculo'), ('Mantenimiento', 'Mantenimiento')], max_length=50, null=True, verbose_name='Objetivo del entrenamiento'),
        ),
        migrations.AlterField(
            model_name='profilespanish',
            name='lifestyle_habits',
            field=models.CharField(blank=True, choices=[('3 comidas', '3 comidas'), ('4 comidas', '4 comidas'), ('5 comidas', '5 comidas'), ('6 comidas', '6 comidas'), ('7 comidas', '7 comidas'), ('8 comidas', '8 comidas')], max_length=20, null=True, verbose_name='Hábitos alimenticios'),
        ),
        migrations.AlterField(
            model_name='profilespanish',
            name='martial_arts',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Correr', 'Correr'), ('Fútbol', 'Fútbol'), ('Natación', 'Natación')], max_length=100, null=True, verbose_name='Artes marciales'),
        ),
        migrations.AlterField(
            model_name='profilespanish',
            name='medical_conditions',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Diabetes', 'Diabetes'), ('Presión arterial alta', 'Presión arterial alta'), ('Enfermedad cardíaca', 'Enfermedad cardíaca')], max_length=100, null=True, verbose_name='Condiciones médicas'),
        ),
        migrations.AlterField(
            model_name='profilespanish',
            name='other_sports',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Correr', 'Correr'), ('Fútbol', 'Fútbol'), ('Natación', 'Natación')], max_length=100, null=True, verbose_name='Otros deportes'),
        ),
        migrations.AlterField(
            model_name='profilespanish',
            name='routine_duration',
            field=models.CharField(blank=True, choices=[('1 Mes', '1 Mes'), ('2 Meses', '2 Meses'), ('3 Meses', '3 Meses'), ('6 Meses', '6 Meses'), ('1 Año', '1 Año')], max_length=20, null=True, verbose_name='Duración de la rutina'),
        ),
        migrations.AlterField(
            model_name='profilespanish',
            name='running',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Correr', 'Correr'), ('Fútbol', 'Fútbol'), ('Natación', 'Natación')], max_length=100, null=True, verbose_name='Correr'),
        ),
        migrations.AlterField(
            model_name='profilespanish',
            name='trainer',
            field=models.CharField(blank=True, choices=[('En casa', 'En casa'), ('En el gimnasio', 'En el gimnasio'), ('Artes marciales', 'Artes marciales'), ('Correr', 'Correr'), ('Otros deportes', 'Otros deportes')], max_length=30, null=True, verbose_name='Entrenador'),
        ),
    ]
