# Generated by Django 5.2.3 on 2025-07-04 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_name', models.CharField(max_length=255)),
                ('time_needed', models.DurationField(help_text='Format: hh:mm:ss')),
                ('for_body_part', models.CharField(max_length=100)),
                ('workout_type', models.CharField(max_length=100)),
                ('calories_burn', models.DecimalField(decimal_places=2, max_digits=6)),
                ('equipment_needed', models.CharField(blank=True, max_length=200)),
                ('tag', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/workouts/')),
                ('benefits', models.TextField(help_text='List benefits separated by commas or lines.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
