# Generated by Django 5.2.3 on 2025-07-11 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutSpanish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(blank=True, help_text='Same as related Workout object', max_length=100, null=True, unique=True)),
                ('workout_name', models.CharField(max_length=255)),
                ('time_needed', models.DurationField(help_text='Formato: hh:mm:ss')),
                ('for_body_part', models.CharField(max_length=100)),
                ('workout_type', models.CharField(max_length=100)),
                ('calories_burn', models.DecimalField(decimal_places=2, max_digits=6)),
                ('equipment_needed', models.CharField(blank=True, max_length=200)),
                ('tag', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/workouts/')),
                ('benefits', models.TextField(help_text='Lista de beneficios separados por comas o líneas.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='workout',
            name='unique_id',
            field=models.CharField(blank=True, help_text='same WorkoutSpanish data', max_length=100, null=True, unique=True),
        ),
    ]
