# Generated by Django 5.2.1 on 2025-07-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='meal_plan_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mealplan',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags for the meal plan', max_length=255),
        ),
    ]
