# Generated by Django 5.2.1 on 2025-07-14 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0002_mealplan_meal_plan_name_mealplan_tags'),
        ('recipe', '0004_alter_recipe_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealentry',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipe.recipe', to_field='unique_id'),
        ),
    ]
