# Generated by Django 5.2.1 on 2025-07-14 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0003_alter_mealentry_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
