# Generated by Django 5.2.1 on 2025-07-14 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0004_mealplan_is_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
