# Generated by Django 5.2.1 on 2025-07-18 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0005_mealplan_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealentry',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mealentry',
            name='eating_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
