# Generated by Django 5.2.3 on 2025-07-27 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0006_mealentry_cancelled_mealentry_eating_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealentry',
            name='grams',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
