# Generated by Django 5.2.3 on 2025-07-29 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0007_mealentry_grams'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealentry',
            name='ingredients_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mealentry',
            name='ingredients_es',
            field=models.TextField(blank=True, null=True),
        ),
    ]
