# Generated by Django 5.2.3 on 2025-07-20 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfect_weight_kg', models.FloatField(help_text='Ideal body weight in kilograms')),
                ('abdominal', models.FloatField(help_text='Abdominal skinfold measurement in mm')),
                ('triceps', models.FloatField(help_text='Triceps skinfold measurement in mm')),
                ('subscapular', models.FloatField(help_text='Subscapular skinfold measurement in mm')),
                ('suprailiac', models.FloatField(help_text='Suprailiac skinfold measurement in mm')),
                ('total_calories_per_day', models.IntegerField(help_text='Estimated daily caloric need')),
                ('water_need_liters_per_day', models.FloatField(help_text='Daily water intake requirement in liters')),
                ('sleep_need_hours_per_day', models.FloatField(help_text='Daily sleep requirement in hours')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
